name: Publish

on:
  push:
    tags:
      - "v*.*.*"


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        token: "${{ secrets.GITHUB_TOKEN }}"
