name: Test
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ELEMENTS_HELPER_APP_ID }}
          private-key: ${{ secrets.ELEMENTS_HELPER_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.3"
      - name: Install dependencies
        run: go get .
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
      - name: Format check
        run: test -z "$(go fmt)"
      - name: Test
        run: go test ./...
  lint-commit:
    runs-on: ubuntu-latest
    name: "Lint commit message"
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install commitizen
        run: |
          python -m pip install --upgrade pip
          python -m pip install commitizen
      - name: Check commit message
        run: cz check --rev-range HEAD
